<form action="/users" method="get">
  <input type="search" name="term" value="<?= htmlspecialchars($term) ?>" />
  <input type="submit" value="Search" />
</form>

<ul>
  <?php foreach ($posts as $post): ?>
    <li>
      <a href="/posts/<?= $post['id'] ?>"><?= $post['name'] ?></a>
    </li>
  <?php endforeach ?>
</ul>

<div>
  <a href="?page=<?= $page < 2 ? 1 : $page - 1 ?>">Prev</a> <a href="?page=<?= $page + 1 ?>">Next</a>
</div>
