<form action="/users" method="get">
  <input type="search" name="term" value="<?= htmlspecialchars($term) ?>" />
  <input type="submit" value="Search" />
</form>

<ul>
  <?php foreach ($users as $user): ?>
    <li>
      <p>
          <?= $user['id'] ?>
      </p>
      <p>
        <a href="/users/<?= $user['id'] ?>"><?= $user['firstName'] ?></a>
      </p>
    </li>
    <?php endforeach ?>
</ul>
